[workspace]
members = ["ether", "main", "service", "tron"]

resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Volodymyr Dotsenko <volodymyrdotsenko@gmail.com>"]
repository = "https://github.com/volodymyrd/cwu"
homepage = "https://github.com/volodymyrd/cwu"
license = "Apache-2.0"
edition = "2024"

[workspace.dependencies]
alloy = "1.1.0"
anyhow = "1"
clap = { version = "4" }
cwu-ether = { version = "0.0.1", path = "ether" }
cwu-service = { version = "0.0.1", path = "service" }
cwu-tron = { version = "0.0.1", path = "tron" }
dialoguer = "0.12.0"
indicatif = "0.18.2"
thiserror = "2.0.17"
tokio = "1.48.0"
tronic = "0.4.0"
url = "2.5.7"
